// <auto-generated />
using APIPractice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIPractice.Migrations
{
    [DbContext(typeof(APIContext))]
    partial class APIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIPractice.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "Ava Reynolds",
                            Title = "The Silent Horizon",
                            YearPublished = 2018
                        },
                        new
                        {
                            ID = 2,
                            Author = "Liam Carter",
                            Title = "Shadows of the Mind",
                            YearPublished = 2020
                        },
                        new
                        {
                            ID = 3,
                            Author = "Maya Thompson",
                            Title = "Echoes of Tomorrow",
                            YearPublished = 2015
                        },
                        new
                        {
                            ID = 4,
                            Author = "Noah Bennett",
                            Title = "The Last Ember",
                            YearPublished = 2022
                        },
                        new
                        {
                            ID = 5,
                            Author = "Sophia Martinez",
                            Title = "Fragments of Light",
                            YearPublished = 2011
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
